### ISSUE TITLE
Some time smart search doesn't work

### ISSUE THREAD

**Issue by yanusa3** [jdi-testing/jdi-light#73] opened 2019-02-06 08:03 UTC
Example 1:
@Css("[qa-item='heading']")
public Heading heading;

public class Heading extends Section {
    public Button button;
}

heading.button.click(); // Element not found

Example 2:
@Css("[qa-item='heading']")
public Heading heading;

public class Heading extends Section {
    @Css("[qa-item='button']")
    public Button button;
}

heading.button.click(); // Element found without problem

**Comment by yanusa3** [comment] 2019-03-11 14:35
1.0.45 - still reproduced

**Comment by AlexeyGirin** [comment] 2019-04-19 09:38
@kasdar23 please investigate and reproduce
Contact with issue reposter via Skype (@RomanIovlev has contact )

**Comment by AlexeyGirin** [comment] 2019-04-23 09:11
@yanusa3 we can't reproduce it. Could you please provide us more details to help us to reproduce it.

**Comment by kasdar23** [comment] 2019-05-07 12:21
yanusa3 sent another example: 
@Css("[qa-item='stage-list-item-wrapper']")
    UIList<StageItem, ?> stageItems;
public class StageItem extends Section {
    public TextField stageTitle;
} 
stageItems.get(size - 1).AddBefore();
  public void AddBefore(){
        stageTitle.hover();
        btnAddStageBefore.click();
    }
Error:
Failed to execute 'hover' for element 'Stage Title' action during '45' seconds. Exception: java.lang.RuntimeException: 
Can't find Element 'StageItem.stageTitle (>css='[qa='document-settings-modal']'>css='[qa-item='stage-list-item-wrapper']'>)' during 45 seconds
java.lang.RuntimeException: 
[20:50.28] 
Failed to execute 'hover' for element 'Stage Title' action during '45' seconds. Exception: java.lang.RuntimeException: 
Can't find Element 'StageItem.stageTitle (>css='[qa='document-settings-modal']'>css='[qa-item='stage-list-item-wrapper']'>)' during 45 seconds
	at com.epam.jdi.light.common.Exceptions.exception(Exceptions.java:12)
	at com.epam.jdi.light.actions.ActionProcessor.jdiAround(ActionProcessor.java:49)
	at com.epam.jdi.light.elements.base.JDIBase.hover(JDIBase.java:413)
	at com.cm.elements.StageItem.AddBefore(StageItem.java:20)
	at com.cm.panels.document.DocumentSettings.addStage(DocumentSettings.java:72)
	at com.cm.tests.Smoke.createTemplate(Smoke.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

error is reproduced in: package io.github.epam.html.tests.issue.issue73;

**Comment by RomanIovlev** [comment] 2019-08-28 23:30
fixed in 1.1

**Closed** 2019-08-28 23:30 UTC
Labels: 1.1, language:java
