### ISSUE TITLE
Update test site: Datepicker element

### ISSUE THREAD

**Issue by b14ckster** [jdi-testing/jdi-light#4929] opened 2023-05-17 08:05 UTC
**CLOSED as duplicate of #4930** 

At the moment the following features are not presented on angular test site for element Datepicker.
test-site: https: jdi-testing.github.io/jdi-light/angular.html
angular site: https://material.angular.io/components/datepicker/overview

[ ] Date range picker forms integration
[ ] 
[ ] 
[ ] 
[ ] 
[ ] 
[ ]

**Comment by MayaElf** [comment] 2023-11-09 09:41
CLOSED as duplicate of https://github.com/jdi-testing/jdi-light/issues/4930

**Closed by MayaElf** 2023-11-09 09:41 UTC
Labels: Angular, TestSite, ReWork
