### ISSUE TITLE
Implement tests related with the rest of  v-slide-group properties

### ISSUE THREAD

**Issue by behhVenn** [jdi-testing/jdi-light#4128] opened 2022-08-01 08:06 UTC
Based on https://vuetifyjs.com/en/components/slide-groups/#usage need to add checks related with v-slide-group properties:

- [ ] dark
- [ ] light
- [ ] max
- [ ] mobile-breakpoint
- [ ] show-arrows
- [ ] tag
- [ ] value
- [ ] value-comparator

**Comment by MayaElf** [comment] 2023-01-05 09:21
duplicate of #4298 
so CLOSED 05 01 23

**Closed by MayaElf** 2023-01-05 09:21 UTC
Labels: Vuetify, Refactoring
