### ISSUE TITLE
Implement checks related with v-slide-group events

### ISSUE THREAD

**Issue by behhVenn** [jdi-testing/jdi-light#4137] opened 2022-08-01 09:58 UTC
Based on https://vuetifyjs.com/en/components/slide-groups/#usage need to update existing code to cover v-slide-group events:
#change
#click:next
#click:prev

**Comment by MayaElf** [comment] 2023-01-04 11:10
Duplicate of #4298 So CLOSED 04 01 23

**Comment by MayaElf** [comment] 2023-01-04 11:10
Duplicate of #4298 So CLOSED 04 01 23

**Closed by MayaElf** 2023-01-04 11:10 UTC
Labels: Vuetify, Refactoring
