### ISSUE TITLE
Fix flaky test: queryProgressLinearTests

### ISSUE THREAD

**Issue by pavelpostnikov1** [jdi-testing/jdi-light#4456] opened 2022-10-24 15:12 UTC
Test is flaky and falls in 2% of times. This happens because tested element changes it's state every 2 seconds from indeterminate to determinate with different values then to hidden and waits can't correctly manage it

**Comment by MayaElf** [comment] 2023-01-11 13:50
closed as duplicate of #4581

**Closed by MayaElf** 2023-01-11 13:50 UTC
Labels: Vuetify, Refactoring
